# Generated by Django 3.0.11 on 2020-12-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='posts/photos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_rating',
            field=models.FloatField(null=True),
        ),
    ]
