# Generated by Django 3.0.11 on 2020-12-03 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20201201_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('text', models.TextField(blank=True)),
                ('comment_rating', models.FloatField(null=True)),
                ('for_user', models.ForeignKey(help_text='User that recives the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_user', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(help_text='User that emits the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
            options={
                'ordering': ['-modified', '-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
