# Generated by Django 3.0.11 on 2020-12-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_rating',
            field=models.FloatField(default=0.0, help_text='Feelings overall rating based on post results'),
        ),
    ]
