# Generated by Django 3.0.11 on 2020-11-27 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('biography', models.TextField(max_length=250)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures', verbose_name='profile picture')),
                ('profile_rating', models.FloatField(default=5.0, help_text='Feelings overall rating based on post results')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified', '-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
